# Generated by Django 4.1.5 on 2023-02-14 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0001_initial"),
        ("solos", "0002_solo_album_solo_end_time_solo_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solo",
            name="album",
        ),
        migrations.AddField(
            model_name="solo",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="solo",
            name="track",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="albums.track",
            ),
        ),
    ]
